output "service_principal_id" {
  description = "The ID of the Service Principal."
  value       = azuread_service_principal.this.object_id
}

output "client_id" {
  description = "The Client ID for the application, which is globally unique."
  value       = azuread_application_registration.this.client_id
}

output "client_secret" {
  value       = var.github_actions_auth_type == "secret" ? azuread_application_password.this[0].value : ""
  description = "The password for this application, which is generated by Azure Active Directory."
  sensitive   = true
}
