#!/usr/bin/env bash
set -euo pipefail

exec docker run --rm \
    --volume "$PWD:/cwd" \
    --workdir "/cwd" \
    --env AWS_SECRET_ACCESS_KEY \
    --env AWS_ACCESS_KEY_ID \
    --env AWS_SESSION_TOKEN \
    --env AWS_SECURITY_TOKEN \
    public.ecr.aws/hashicorp/terraform:1.6.6@sha256:9a42ea97ea25b363f4c65be25b9ca52b1e511ea5bf7d56050a506ad2daa7af9d \
    "$@"
